import type { Case, Statute, Contract, AnalysisJob, AuditEntry, Workflow } from './mcp/types'

export const CASES: Case[] = [
  {
    id: 'smith-v-abc-corp-2022',
    name: 'Smith v. ABC Corp',
    citation: '2022 Cal.App.4th 1234',
    court: 'California Court of Appeal',
    jurisdiction: 'CA',
    year: 2022,
    topics: ['contract breach', 'delivery timing', 'time is of the essence'],
    holding: 'Time is of the essence clauses must be explicitly stated and cannot be implied from the circumstances alone.',
    summary: 'The court held that where a commercial contract does not expressly state that time is of the essence, a reasonable-time standard governs delivery obligations.',
    disposition: 'Judgment for plaintiff affirmed in part.',
    relevance_score: 0.97,
    cites: ['johnson-v-xyz-industries-2020'],
  },
  {
    id: 'johnson-v-xyz-industries-2020',
    name: 'Johnson v. XYZ Industries',
    citation: '2020 Cal.4th 567',
    court: 'California Supreme Court',
    jurisdiction: 'CA',
    year: 2020,
    topics: ['contract breach', 'delivery terms', 'reasonable time'],
    holding: 'Commercial contracts are presumed to include reasonable delivery terms informed by industry standards.',
    summary: 'The California Supreme Court clarified that industry standards are relevant, though not dispositive, when determining a reasonable time for performance.',
    disposition: 'Reversed and remanded.',
    relevance_score: 0.91,
    cites: [],
  },
  {
    id: 'davis-v-tech-solutions-2021',
    name: 'Davis v. Tech Solutions',
    citation: '2021 Cal.App.4th 890',
    court: 'California Court of Appeal',
    jurisdiction: 'CA',
    year: 2021,
    topics: ['material breach', 'damages', 'substantial non-performance'],
    holding: 'A material breach requires substantial non-performance; minor delays are generally not material.',
    summary: 'The court defined the threshold for material breach in commercial delivery disputes and addressed the calculation of foreseeable damages.',
    disposition: 'Affirmed.',
    relevance_score: 0.85,
    cites: ['johnson-v-xyz-industries-2020'],
  },
  {
    id: 'hadley-v-baxendale-1854',
    name: 'Hadley v. Baxendale',
    citation: '156 Eng. Rep. 145',
    court: 'Court of Exchequer',
    jurisdiction: 'UK',
    year: 1854,
    topics: ['consequential damages', 'foreseeability', 'contract breach'],
    holding: 'Consequential damages are recoverable only where they were reasonably foreseeable at the time of contracting.',
    summary: 'The foundational rule on the foreseeability of contract damages, still routinely cited in United States commercial litigation.',
    disposition: 'New trial ordered.',
    relevance_score: 0.78,
    cites: [],
  },
  {
    id: 'northstar-v-delta-2023',
    name: 'Northstar Capital LLC v. Delta Ventures',
    citation: '2023 Del. Ch. 412',
    court: 'Delaware Court of Chancery',
    jurisdiction: 'DE',
    year: 2023,
    topics: ['fiduciary duty', 'merger agreement', 'earnout dispute'],
    holding: "A board's failure to disclose material synergies in an earnout schedule constitutes a breach of fiduciary duty to minority shareholders.",
    summary: 'The court awarded equitable relief after finding management withheld forecasted synergies during vote on acquisition earnout terms.',
    disposition: 'Relief granted in part.',
    relevance_score: 0.72,
    cites: [],
  },
]

export const STATUTES: Statute[] = [
  {
    id: 'Cal.Civ.Code.1657',
    title: 'Reasonable Time for Performance',
    jurisdiction: 'CA',
    citation: 'Cal. Civ. Code § 1657',
    text: 'Where no time is specified for the performance of an act required to be performed, a reasonable time is allowed. If the act is in its nature capable of being done instantly, it must be performed immediately, or at least within such time as may be necessary for the performance of the act.',
    enacted: '1872',
    last_amended: '1983',
    history: 'Enacted in 1872 as part of the original California Civil Code; amended in 1983 for a minor language clarification. Codifies the common-law reasonable-time principle for contract performance.',
    topics: ['reasonable time', 'contract performance', 'default timing'],
  },
  {
    id: 'Cal.Com.Code.2106',
    title: 'Definitions: Conforming to Contract; Termination; Cancellation',
    jurisdiction: 'CA',
    citation: 'Cal. Com. Code § 2106',
    text: "In this division unless the context otherwise requires 'contract' and 'agreement' are limited to those relating to the present or future sale of goods. Goods or conduct including any part of a performance are 'conforming' or conform to the contract when they are in accordance with the obligations under the contract.",
    enacted: '1963',
    last_amended: '2006',
    history: "Part of California's adoption of the Uniform Commercial Code, Division 2 (Sales).",
    topics: ['sale of goods', 'conforming performance', 'UCC'],
  },
  {
    id: '18.USC.1030',
    title: 'Computer Fraud and Abuse Act',
    jurisdiction: 'Federal',
    citation: '18 U.S.C. § 1030',
    text: 'Whoever knowingly accesses a computer without authorization or exceeds authorized access, and thereby obtains information contained in a financial record of a financial institution shall be punished as provided in subsection (c).',
    enacted: '1986',
    last_amended: '2008',
    history: 'Originally enacted as the Counterfeit Access Device and Computer Fraud and Abuse Act of 1984; substantially amended in 1986, 1994, 1996, 2001, and 2008.',
    topics: ['computer fraud', 'unauthorized access', 'cybersecurity', 'criminal liability'],
  },
  {
    id: 'GDPR.Art.28',
    title: 'GDPR Article 28 — Processor',
    jurisdiction: 'EU',
    citation: 'GDPR Art. 28',
    text: 'Where processing is to be carried out on behalf of a controller, the controller shall use only processors providing sufficient guarantees to implement appropriate technical and organisational measures in such a manner that processing will meet the requirements of this Regulation and ensure the protection of the rights of the data subject.',
    enacted: '2016',
    last_amended: '2018',
    history: 'Part of Regulation (EU) 2016/679 (GDPR), effective 25 May 2018.',
    topics: ['data processing', 'processor obligations', 'GDPR', 'data protection'],
  },
]

export const CONTRACTS: Contract[] = [
  {
    id: 'standard_nda_template',
    title: 'Standard Mutual Non-Disclosure Agreement',
    type: 'NDA',
    risk_level: 'MEDIUM',
    clauses: [
      { key: 'confidentiality_scope', label: 'Confidentiality Scope', text: "Recipient shall hold in strict confidence all proprietary information disclosed by the Disclosing Party, including all technical, business, and financial information, whether or not marked confidential.", risk: 'LOW', risk_note: 'Broad scope favors disclosing party. Standard language.' },
      { key: 'term_duration', label: 'Term & Duration', text: 'The obligations of confidentiality shall survive for five (5) years following termination of this Agreement.', risk: 'LOW', risk_note: '5-year survival is standard for commercial NDAs.' },
      { key: 'return_of_materials', label: 'Return of Materials', text: 'Upon termination, Recipient shall return or destroy all Confidential Materials within thirty (30) days.', risk: 'LOW', risk_note: '30-day window is standard. Consider adding a certification requirement.' },
      { key: 'governing_law', label: 'Governing Law', text: 'This Agreement shall be governed by the laws of the State of California.', risk: 'LOW', risk_note: 'California is an acceptable jurisdiction for commercial agreements.' },
      { key: 'remedies', label: 'Remedies', text: 'The Disclosing Party shall be entitled to seek injunctive relief in addition to any other remedies available at law or in equity.', risk: 'LOW', risk_note: 'Standard injunctive relief provision.' },
    ],
    missing_clauses: ['indemnification', 'dispute_resolution', 'limitation_of_liability'],
    parties: { disclosing: 'Client Corp', receiving: 'Vendor LLC' },
    governing_law: 'California',
    term: '2 years',
    liability_cap: null,
  },
  {
    id: 'client_proposed_nda',
    title: 'Client Proposed Non-Disclosure Agreement',
    type: 'NDA',
    risk_level: 'HIGH',
    clauses: [
      { key: 'confidentiality_scope', label: 'Confidentiality Scope', text: "Recipient shall hold in confidence only information that is specifically marked 'Confidential' at the time of disclosure.", risk: 'HIGH', risk_note: 'Narrowly scoped — only marked materials protected. Oral disclosures unprotected. Consider broadening.' },
      { key: 'term_duration', label: 'Term & Duration', text: 'The obligations of confidentiality shall survive for three (3) years following termination of this Agreement.', risk: 'MEDIUM', risk_note: '3-year survival is below the 5-year market standard. Recommend extending.' },
      { key: 'return_of_materials', label: 'Return of Materials', text: 'Upon termination, Recipient shall return or destroy all Confidential Materials within sixty (60) days.', risk: 'MEDIUM', risk_note: '60-day window is longer than standard 30 days. Creates extended exposure window.' },
      { key: 'governing_law', label: 'Governing Law', text: 'This Agreement shall be governed by the laws of the State of California.', risk: 'LOW', risk_note: 'California jurisdiction acceptable.' },
      { key: 'indemnification', label: 'Indemnification', text: 'Recipient shall indemnify and hold harmless the Disclosing Party against any and all losses arising from unauthorized disclosure, without limitation of liability.', risk: 'CRITICAL', risk_note: 'Unlimited indemnification with no liability cap is highly unusual and risky. Negotiate a cap.' },
    ],
    missing_clauses: ['remedies', 'dispute_resolution', 'limitation_of_liability'],
    parties: { disclosing: 'Client Corp', receiving: 'Vendor LLC' },
    governing_law: 'California',
    term: '3 years',
    liability_cap: null,
  },
  {
    id: 'master_services_agreement_tech',
    title: 'Master Services Agreement — Technology & Software',
    type: 'MSA',
    risk_level: 'MEDIUM',
    clauses: [
      { key: 'scope_of_services', label: 'Scope of Services', text: 'Provider shall develop, deliver, and maintain the software and technology services described in mutually executed Statements of Work.', risk: 'LOW', risk_note: 'Clear scope delegation to SOWs. Standard approach.' },
      { key: 'intellectual_property', label: 'Intellectual Property', text: "All work product, code, and deliverables created by Provider specifically for Client under this Agreement shall be works-made-for-hire. Provider retains ownership of its pre-existing tools, frameworks, and methodologies ('Background IP').", risk: 'MEDIUM', risk_note: 'Works-for-hire favorable for client but review Background IP carve-out scope carefully.' },
      { key: 'data_security', label: 'Data Security', text: 'Provider shall maintain industry-standard security controls, including encryption in transit and at rest, access controls, and annual penetration testing. Provider shall notify Client of any confirmed security incident within forty-eight (48) hours.', risk: 'LOW', risk_note: '48-hour incident notification is standard. SOC 2 attestation should be referenced.' },
      { key: 'limitation_of_liability', label: 'Limitation of Liability', text: "Each party's aggregate liability shall not exceed the greater of (i) fees paid in the twelve (12) months preceding the claim or (ii) $500,000. Liability for gross negligence, willful misconduct, or IP infringement is not capped.", risk: 'LOW', risk_note: 'Balanced cap with appropriate carve-outs for gross negligence and IP.' },
      { key: 'dispute_resolution', label: 'Dispute Resolution', text: 'Disputes shall first be escalated to senior management for good-faith negotiation. Unresolved disputes shall be submitted to binding arbitration under JAMS rules in San Francisco, California.', risk: 'LOW', risk_note: 'JAMS arbitration is standard. Consider specifying arbitrator selection process.' },
    ],
    missing_clauses: [],
    parties: { provider: 'TechVendor Inc.', client: 'Enterprise Corp' },
    governing_law: 'Delaware',
    term: '2 years, auto-renewing',
    liability_cap: '$500,000',
  },
]

export const JOBS: AnalysisJob[] = [
  { id: 'job-001', file: 'vendor_nda_2026.docx', status: 'complete', queued_at: '2026-07-07T02:03:11Z', completed_at: '2026-07-07T02:03:44Z', risk_level: 'HIGH', clause_count: 12, flags: 3 },
  { id: 'job-002', file: 'saas_msa_draft.docx', status: 'complete', queued_at: '2026-07-07T02:05:00Z', completed_at: '2026-07-07T02:05:28Z', risk_level: 'MEDIUM', clause_count: 9, flags: 1 },
  { id: 'job-003', file: 'dpa_addendum_eu.pdf', status: 'processing', queued_at: '2026-07-07T02:08:55Z', completed_at: null, risk_level: null, clause_count: null, flags: null },
  { id: 'job-004', file: 'advisor_agreement_v3.docx', status: 'queued', queued_at: '2026-07-07T02:09:10Z', completed_at: null, risk_level: null, clause_count: null, flags: null },
  { id: 'job-005', file: 'hipaa_baa_template.docx', status: 'error', queued_at: '2026-07-07T02:01:00Z', completed_at: '2026-07-07T02:01:03Z', risk_level: null, clause_count: null, flags: null, error: 'File parse error: unsupported encryption format' },
]

export const AUDIT_LOG: AuditEntry[] = [
  { id: 'a-001', timestamp: '2026-07-07T02:03:11Z', tool: 'queue_document_analysis', user: 'attorney', category: 'analysis', input: { file: 'vendor_nda_2026.docx' }, success: true, duration_ms: 42 },
  { id: 'a-002', timestamp: '2026-07-07T02:03:44Z', tool: 'get_analysis_result', user: 'attorney', category: 'analysis', input: { job_id: 'job-001' }, success: true, duration_ms: 18 },
  { id: 'a-003', timestamp: '2026-07-07T02:04:02Z', tool: 'analyze_clauses', user: 'attorney', category: 'contract', input: { contract_id: 'client_proposed_nda' }, success: true, duration_ms: 310 },
  { id: 'a-004', timestamp: '2026-07-07T02:04:18Z', tool: 'suggest_clause_alternatives', user: 'attorney', category: 'contract', input: { clause_type: 'indemnification' }, success: true, duration_ms: 195 },
  { id: 'a-005', timestamp: '2026-07-07T02:05:00Z', tool: 'queue_document_analysis', user: 'attorney', category: 'analysis', input: { file: 'saas_msa_draft.docx' }, success: true, duration_ms: 35 },
  { id: 'a-006', timestamp: '2026-07-07T02:05:28Z', tool: 'get_analysis_result', user: 'attorney', category: 'analysis', input: { job_id: 'job-002' }, success: true, duration_ms: 22 },
  { id: 'a-007', timestamp: '2026-07-07T02:06:10Z', tool: 'search_precedents', user: 'attorney', category: 'search', input: { query: 'breach of contract delivery' }, success: true, duration_ms: 88 },
  { id: 'a-008', timestamp: '2026-07-07T02:06:45Z', tool: 'validate_citation', user: 'attorney', category: 'validation', input: { citation: '2022 Cal.App.4th 1234' }, success: true, duration_ms: 14 },
  { id: 'a-009', timestamp: '2026-07-07T02:07:30Z', tool: 'check_privilege_risk', user: 'attorney', category: 'privilege', input: { file: 'litigation_memo.docx', provider: 'openai' }, success: true, duration_ms: 54 },
  { id: 'a-010', timestamp: '2026-07-07T02:08:55Z', tool: 'queue_document_analysis', user: 'attorney', category: 'analysis', input: { file: 'dpa_addendum_eu.pdf' }, success: true, duration_ms: 38 },
  { id: 'a-011', timestamp: '2026-07-07T02:09:10Z', tool: 'queue_document_analysis', user: 'attorney', category: 'analysis', input: { file: 'advisor_agreement_v3.docx' }, success: false, duration_ms: 3200 },
  { id: 'a-012', timestamp: '2026-07-07T02:10:00Z', tool: 'generate_negotiation_guide', user: 'attorney', category: 'contract', input: { contract_id: 'client_proposed_nda', party_role: 'buyer' }, success: true, duration_ms: 241 },
]

export const WORKFLOWS: Workflow[] = [
  {
    id: 'contract-risk-triage', mnemonic: 'CTRX', title: 'Contract Risk Triage',
    trigger: 'Review a contract, compare two NDAs, identify risky clauses',
    steps: [
      { n: 1, tool: 'analyze_document / analyze_clauses', desc: 'Run clause-level risk analysis on the contract' },
      { n: 2, tool: 'compare_documents / compare_contracts', desc: 'Diff two versions side-by-side if applicable' },
      { n: 3, tool: 'suggest_clause_alternatives', desc: 'Get rewrite options for flagged clauses' },
      { n: 4, tool: 'deep_analyze_clause', desc: 'Deep reasoning on highest-risk clause (MCP sampling)' },
      { n: 5, tool: 'export_analysis_report', desc: 'Export formatted .docx risk report' },
    ],
  },
  {
    id: 'negotiation-prep', mnemonic: 'NEGO', title: 'Negotiation Prep',
    trigger: "Buyer/seller wants to know what to push back on",
    steps: [
      { n: 1, tool: 'generate_negotiation_guide', desc: 'Per-clause accept/negotiate/reject guide with fallback language' },
      { n: 2, tool: 'suggest_clause_alternatives', desc: "Alternative phrasings for clauses flagged 'negotiate'" },
      { n: 3, tool: 'analyze_document', desc: 'If real file: run analyze_document first, apply logic manually' },
    ],
  },
  {
    id: 'metadata-lookup', mnemonic: 'META', title: 'Contract Metadata Lookup',
    trigger: 'What is the governing law / term / liability cap in this contract',
    steps: [{ n: 1, tool: 'extract_contract_metadata', desc: 'Extract parties, dates, governing law, term, liability cap, payment terms as JSON' }],
  },
  {
    id: 'privilege-safe-review', mnemonic: 'PRIV', title: 'Privilege-Safe AI Review',
    trigger: 'Can I paste this into ChatGPT / Claude? Is this privileged?',
    steps: [
      { n: 1, tool: 'check_privilege_risk', desc: 'Assess routing risk against Heppner and ABA Rule 1.6' },
      { n: 2, tool: '(advisory)', desc: 'On HIGH/CRITICAL: advise against routing; suggest ollama (local, zero-retention)' },
    ],
  },
  {
    id: 'legal-research', mnemonic: 'PREC', title: 'Legal Research',
    trigger: 'Find precedents for …, what does this statute say, research this issue',
    steps: [
      { n: 1, tool: 'search_precedents / search_case_law', desc: 'Keyword-ranked case search across local seed data' },
      { n: 2, tool: 'extract_statute', desc: 'Full statutory text with legislative history' },
      { n: 3, tool: 'research_legal_issue', desc: 'Multi-source: cases + statutes + optional CourtListener' },
      { n: 4, tool: 'validate_citation', desc: 'Validate every citation before presenting' },
      { n: 5, tool: 'search_live_case_law', desc: 'Live CourtListener/PACER query (only if local results insufficient and integration enabled)' },
    ],
  },
  {
    id: 'brief-drafting', mnemonic: 'BRF', title: 'Brief / Motion Drafting',
    trigger: 'Draft a motion, outline this brief, argument structure',
    steps: [
      { n: 1, tool: 'generate_brief_outline', desc: 'Outline from brief framework by case type' },
      { n: 2, tool: 'create_argument_structure', desc: 'IRAC-style argument scaffold' },
      { n: 3, tool: 'generate_issue_statement', desc: 'Issue-statement framework from facts + law' },
      { n: 4, tool: 'search_precedents', desc: 'Pull supporting precedents for each argument' },
    ],
  },
  {
    id: 'citation-cleanup', mnemonic: 'CITE', title: 'Citation Cleanup',
    trigger: 'Validate citations, normalize Bluebook format, check integrity',
    steps: [
      { n: 1, tool: 'validate_citation', desc: 'Validate citation structure and reporter' },
      { n: 2, tool: 'normalize_citation', desc: 'Normalize to Bluebook-style abbreviations' },
      { n: 3, tool: 'verify_citation_integrity', desc: 'Cross-check citation against case database' },
    ],
  },
  {
    id: 'batch-analysis', mnemonic: 'JOBS', title: 'Batch Document Analysis',
    trigger: 'Analyze multiple contracts or documents in the background',
    steps: [
      { n: 1, tool: 'queue_document_analysis', desc: 'Queue each document; receive job IDs' },
      { n: 2, tool: 'list_analysis_jobs', desc: 'List all jobs with status and timestamps' },
      { n: 3, tool: 'get_analysis_status', desc: 'Poll status for in-progress jobs' },
      { n: 4, tool: 'get_analysis_result', desc: 'Retrieve completed analysis result' },
    ],
  },
]
